server:  
  port: 8888
spring:  
  application:
    name: configserver  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/profeInformatica101/microservicios.git
          search-paths: config
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  security:
   user:
      name: root
      password: s3cr3t
   
   